#!/bin/sh
#
# CVL build system to check or configure building process after installation.
#

SOURCE_DIR=$1
BUILD_DIR=$2
INSTALL_DIR=$3

if [ ! -d ${INSTALL_DIR}/bin ]; then
    mkdir ${INSTALL_DIR}/bin
fi

cp ${BUILD_DIR}/pymol ${INSTALL_DIR}/bin
cp ${SOURCE_DIR}/document ${INSTALL_DIR}/bin
cp ${SOURCE_DIR}/pymol_icon.png ${INSTALL_DIR}

# Pmw plugin
pushd ${SOURCE_DIR}/pmw/src/
python setup.py install --prefix=${INSTALL_DIR}
popd

# Copy module validation script to package directory.
if [ ! -f ${INSTALL_DIR}/validate_module.sh ]; then
    cp ${SOURCE_DIR}/validate_module.sh ${INSTALL_DIR}
fi
